packages:
  - "apps/*"
  - "libs/*"
allowBuilds:
  '@swc/core': true
  b: true
  d: true
  e: true
  i: true
  l: true
  s: true
  u: true
catalog:
  zod: 4.4.3
  prettier: 3.8.4
  typescript: 5.9.3
  vitest: 4.1.8
