services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ardoise
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ardoise
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
